### ISSUE TITLE
Support piping output of one cell into another

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/bashbook#10]
For consistency with behaviour in jupyter notebooks, we could use `$_` for the output of the previous cell in execution order, and `$_3` for the cell at execution order 3

**Comment by AndreasArvidsson** [comment]
`$_` is already a bash command so we are going to have to find something else

**Comment by pokey** [comment]
Ah right was worried bout that. What does it do again?

**Comment by AndreasArvidsson** [comment]
It contains the last argument

I now have a working implementation of this using the syntax `$:` `:5`
