### ISSUE TITLE
Support saving text output to a file

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/bashbook#21]

**Comment by AndreasArvidsson** [comment]
Ok this is irritating. If we only output plain text the file only contains that output. But if you have multiple mime types you get this json output with the actual payload. Since the plain text renderer is part of vscode I don't know if we can actually affect this.

**Comment by pokey** [comment]
That's annoying. I wonder if that's how it works with images too

**Comment by AndreasArvidsson** [comment]
If we really want this the correct solution is probably to create our own plaintext renderer. Definitely simpler then that terminal one we have now. But not too high upon my to do.

**Comment by pokey** [comment]
Yeah let's just leave it open for now; if we find ourselves wanting this a lot we can find a way to fix it.  For now if you're in an active session you can just do `echo "$:n" > file.txt`, right?

**Comment by AndreasArvidsson** [comment]
Should probably work

**Comment by AndreasArvidsson** [comment]
There is now a button on the top of the notebook and on each cell for storing the output in a new plaintext file.
