### ISSUE TITLE
Fix path autocomplete when you ask for autocomplete at the end of a path prefix

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/bashbook#24]

**Comment by AndreasArvidsson** [comment]
Can you give an example of this?
`cd ~/.an` for example works fine for me

**Comment by AndreasArvidsson** [comment]
I have made a few updates to this code. Please try it out

**Comment by pokey** [comment]
Reopening because this appears to still be an issue. To recreate have a cell with the following contents:

```
cd src/
```

Where the working directory is `~/src/bashbook`

There seems to be a weirdness where a slash is pretended to the beginning of the string so the debug output that we get from the autocomplete is

```
/~/src/bashbook/src
```

**Comment by AndreasArvidsson** [comment]
Ok I wasn't handling cwd starting with `~`. Now this should definitely be closed :D
