### ISSUE TITLE
Add icons for completions

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/bashbook#39]
Can use the [`kind` argument](https://code.visualstudio.com/api/references/vscode-api#CompletionItem).

- [x] Should use `File` for paths
- [x] For previous commands, I've seen `Event` used in a similar context, and it shows up with a nice little lightning bolt (see https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions)

**Comment by AndreasArvidsson** [comment]
We already do that
https://github.com/AndreasArvidsson/bashbook/blob/master/src/extension/languageProvider.ts#L146

**Comment by AndreasArvidsson** [comment]
Changed history kind from text to event
