### ISSUE TITLE
Strange horizontal bar appearing below cell

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/bashbook#41]
See screenshot:

![image](https://user-images.githubusercontent.com/755842/151601999-fac1f81c-585f-4302-b619-bf83c98eae09.png)

This only appears the first time you run a cell, and disappears if you re-run the cell.  It does not happen with Jupyter notebooks

**Comment by AndreasArvidsson** [comment]
That looks like the horizontal scrollbar. Remember it's not until after we run the first command that we resize/update number of columns.

**Comment by pokey** [comment]
And so you are correct 😅.  Do we have an issue to track a proper fix for that one?  Worth making such an issue?

**Comment by AndreasArvidsson** [comment]
Please file issues for anything you find that doesn't work as you expected it to. You could just update this issue or close it and create a new one.
