### ISSUE TITLE
Add support for mac and linux

### ISSUE THREAD

**Issue by AndreasArvidsson** [AndreasArvidsson/bashbook#42]
Because of node-pty we have to have platform specific binaries. 

I have already tried publishing it with different targets, but currently only the windows binary works on the marketplace. 
`"vscode:publish": "vsce publish --target win32-x64 linux-x64 darwin-x64 darwin-arm64"`

* [x] mac
* [x] linux

**Comment by AndreasArvidsson** [comment]
@pokey Using the bashbook from the marketplace is now working on mac, correct?

**Comment by pokey** [comment]
Correct 👍

**Comment by AndreasArvidsson** [comment]
Great! Then I just need to figure out linux.

**Comment by AndreasArvidsson** [comment]
Turns out that on ubuntu you need to install vscode using `apt install` and flatpack does not work. For now this is a workable solution.

**Comment by AndreasArvidsson** [comment]
I have indications from a user that bash book is working on ubuntu when vscode is NOT installed from flatpack.
