### ISSUE TITLE
Extension Not Working Generally

### ISSUE THREAD

**Issue by C-Loftus** [AndreasArvidsson/bashbook#53]
I am Running ubuntu 22.04 with visual studio code installed through apt as the read me says.  I have restarted visual studio code but I continued to get the error that  there is no extension associated with  the file type `.bashbook`.  The command to generate a new bash book file also seems to be missing. I have attached images here. I'm not sure if I'm doing something wrong

 thank you for your work
![image](https://user-images.githubusercontent.com/70598503/227607657-ec698b93-8a74-4121-b404-96c9f9d786b2.png)
![image](https://user-images.githubusercontent.com/70598503/227607836-a43a6044-683c-487f-ba03-4deee27e0282.png)

**Comment by AndreasArvidsson** [comment]
Can you open your developer tools(`workbench.action.toggleDevTools`) and see if you're getting the `NODE_MODULE_VERSION ` error?
https://github.com/AndreasArvidsson/bashbook#rebuild-node-pty-with-correct-electron-version

**Comment by C-Loftus** [comment]
Thank you that was it.   I did not realize that was in the developer tools.

**Comment by AndreasArvidsson** [comment]
This is unfortunately quite problematic. Due to using `node-pty` we have platform specific dependencies. It also needs to be built for a specific electron version. That means that sometimes when there is a new vscode version bash book needs to rebuilt.
